spring.application.name=project
server.port=8081
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.q8ihgre.mongodb.net/mapdb?retryWrites=true&w=majority

spring.ai.google.genai.api-key=AIzaSyB343v0z48SG5IJKn-CrWYovuLo5PhqMHk
spring.ai.google.genai.chat.options.model=gemini-flash-latest

