spring.application.name=project
server.port=8081
spring.data.mongodb.uri={mongo_db}

spring.ai.google.genai.api-key={gemini_key}
spring.ai.google.genai.chat.options.model=gemini-flash-latest

apify.api.token={apify_key}



