spring.application.name=project
server.port=8081
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.q8ihgre.mongodb.net/mapdb?retryWrites=true&w=majority

spring.ai.google.genai.api-key=${gemini_Key}
spring.ai.google.genai.chat.options.model=gemini-flash-latest
apify.api.token=${apify_key}

